spice_up_coordinator:
  username: "carmensc"
  in_simulation_mode: False
  mesh_file_path: "/home/carmensc/ros/catkin_ws/src/alma_rsl/dependencies/spice_up_coordinator/data/kallax_narrow_in_meters.obj"
  debug: True
